
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MAHE
 */
public class Enroll extends javax.swing.JFrame {

    /**
     * Creates new form Enroll
     */
    public static String uid="101";

    public Enroll() {
        initComponents();
    }

    public Enroll(String a) {
        initComponents();
        uid = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 40));

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 240, -1));

        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 240, -1));

        jButton2.setBackground(new java.awt.Color(97, 212, 195));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("PASSWORD");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("USER ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 170, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 260, 10));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("COURSES");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 40));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BACK");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollment.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 320, 270));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 470));

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ENROLL");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("DURATION (WEEKS)");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("COST");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 141, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 141, -1));

        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 153, -1));

        jButton1.setBackground(new java.awt.Color(97, 212, 195));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enroll");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 130, 50));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("SELECT AN ACTIVITY");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 390, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
        try {
            
            
            DefaultListModel m1 = (DefaultListModel) jList1.getModel();
            m1.removeAllElements();
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/kaddle", "root", "@spireE1");
            Statement stmt = con.createStatement();
            String q1 = "select name from activity;";
            ResultSet rs = stmt.executeQuery(q1);
            while (rs.next()) {
                m1.addElement(rs.getString(1));
            }

            if (m1.isEmpty()) {
                JOptionPane.showMessageDialog(this, "There Are No Activities available at the Moment");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jList1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Kaddle", "root", "@spireE1");
            Statement stmt = con.createStatement();
            String q1 = "Select act_id from activity where name='" + jList1.getSelectedValue() + "';";
            ResultSet rs = stmt.executeQuery(q1);
            rs.next();
            String aid = rs.getString(1);
            String q2 = "Select * from participating where act_id='" + aid + "' and user_id='" + uid + "';";
            rs = stmt.executeQuery(q2);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "You have already registered for this activity");
            } else {
                String q4 = "select type from user where user_id='" + uid + "';";
                rs = stmt.executeQuery(q4);
                rs.next();
                if (rs.getString(1).equals("Minor")) {
                    String p_pass = JOptionPane.showInputDialog(this, "To confirm that you are booking this course under the supervision of your parent, please ask him/her to Enter their password");
                    String q5 = "select password from user where user_id=(select parent_id from user where user_id='" + uid + "') ;";
                    rs = stmt.executeQuery(q5);
                    rs.next();
                    if (rs.getString(1).equals(p_pass)) {
                        String q3 = "insert into participating values('" + uid + "','" + aid + "');";
                        stmt.executeUpdate(q3);
                        //JOptionPane.showMessageDialog(this, "Successfully Inserted");
                        PaymentsPage pp = new PaymentsPage(jTextField1.getText());
                        pp.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "The Password entered is incorrect");
                    }
                } else {
                    String q3 = "insert into participating values('" + uid + "','" + aid + "');";
                    stmt.executeUpdate(q3);
                    //JOptionPane.showMessageDialog(this, "Successfully Inserted");
                    PaymentsPage pp = new PaymentsPage(jTextField1.getText());
                    pp.setVisible(true);

                }
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jList1.clearSelection();
            jButton1.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            jTextField1.setText("");
            jTextField2.setText("");
            jList1.clearSelection();
            jButton1.setEnabled(false);
        }
        jList1.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:

        try {
            //jTextField3.setText("");
            //DefaultListModel m1 = (DefaultListModel) jList1.getModel();
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/kaddle", "root", "@spireE1");
            Statement stmt = con.createStatement();
            String val = (String) jList1.getSelectedValue();
            String q1 = "select cost,duration from activity where name='" + val + "';";
            ResultSet rs = stmt.executeQuery(q1);
            rs.next();
            //m1.removeAllElements();
            jTextField1.setText(rs.getString(1));
            jTextField2.setText(rs.getString(2));
            jButton1.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please Enter a User ID", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jPasswordField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please Enter a Password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/kaddle", "root", "@spireE1");
                Statement stmt = con.createStatement();
                String q1 = "";
                if (jTextField1.getText().charAt(0) == '1') {
                    q1 = "select password,Type from user where user_id='" + jTextField1.getText() + "';";
                    ResultSet rs = stmt.executeQuery(q1);

                } else if (jTextField1.getText().charAt(0) == '2') {
                }
                if (!(jTextField1.getText().charAt(0) == '2' || jTextField1.getText().charAt(0) == '1')) {
                    JOptionPane.showMessageDialog(this, "Incorrect Credentials", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (jTextField1.getText().charAt(0) == '1') {
                        q1 = "select password,Type from user where user_id='" + jTextField1.getText() + "';";
                    } else if (jTextField1.getText().charAt(0) == '2') {
                        q1 = "select password from teacher where prof_id='" + jTextField1.getText() + "';";
                    }

                    ResultSet rs = stmt.executeQuery(q1);
                    //rs.next();
                    if (!(rs.next())) {
                        JOptionPane.showMessageDialog(this, "Incorrect User_ID", "Error", JOptionPane.ERROR_MESSAGE);
                        jTextField1.setText("");
                        jPasswordField1.setText("");
                    } else {
                        if (!(rs.getString(1).equals(jPasswordField1.getText()))) {
                            JOptionPane.showMessageDialog(this, "Incorrect Password", "Error", JOptionPane.ERROR_MESSAGE);
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                        } else {
                            //Achtung!! Remove the line below:
                            JOptionPane.showMessageDialog(this, "Login Successful");

                            if (jTextField1.getText().charAt(0) == '1') {
                                if (rs.getString(2).equals("Major")) {
                                    new MajorHomePage().setVisible(true);
                                } else if (rs.getString(2).equals("Minor")) {
                                    new MinorHomePage().setVisible(true);
                                } else {
                                    JOptionPane.showMessageDialog(this, "Incorrect Credentials", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                                this.dispose();
                            } else if (jTextField1.getText().charAt(0) == '2') {
                                new TeacherHomePage(jTextField1.getText()).setVisible(true);
                                this.dispose();
                            }
                        }
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //
        //Feel free to delete the code below
        //
        /*if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please Enter a User ID", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jPasswordField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please Enter a Password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/kaddle", "root", "");
                Statement stmt = con.createStatement();
                String q1="";
                if (jTextField1.getText().charAt(0) == '1')
                q1 = "select password,Type from user where user_id='" + jTextField1.getText() + "';";
                else if (jTextField1.getText().charAt(0) == '2')
                q1 = "select password from teacher where prof_id='" + jTextField1.getText() + "';";

                ResultSet rs = stmt.executeQuery(q1);
                //rs.next();
                if (!(rs.next())) {
                    JOptionPane.showMessageDialog(this, "Incorrect User_ID", "Error", JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                } else {
                    if (!(rs.getString(1).equals(jPasswordField1.getText()))) {
                        JOptionPane.showMessageDialog(this, "Incorrect Password", "Error", JOptionPane.ERROR_MESSAGE);
                        jTextField1.setText("");
                        jPasswordField1.setText("");
                    } else {
                        //Achtung!! Remove the line below:
                        JOptionPane.showMessageDialog(this, "Login Successful");

                        if (jTextField1.getText().charAt(0) == '1') {
                            if (rs.getString(2).equals("Major")) {
                                new MajorHomePage().setVisible(true);
                            } else if (rs.getString(2).equals("Minor")) {
                                new MinorHomePage().setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(this, "Incorrect Credentials", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                            this.dispose();
                        } else if (jTextField1.getText().charAt(0) == '2') {
                            new TeacherHomePage().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Incorrect Credentials", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
            }
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked
        // TODO add your handling code here:
        new MajorHomePage().setVisible(true);
        this.hide();
    }//GEN-LAST:event_clicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
